
model:
  backbone:
    pretrained: '/search/odin/tk/.torch/models/resnet50-19c8e357.pth'
  midneck:
    name: 'single_bnneck'

data:
  transforms: ['random_flip', 'pad', 'random_erase']
  sources: ['market1501']
  targets: ['market1501']

head:
  name: 'softmax'

loss:
  name: ['triplet', 'center', 'crossentropy']

train:
  batch_size: 64

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 64
  normalize_feature: True
  rerank: True
  eval_freq: 40