
model:
  midneck:
    name: 'single_bnneck'

data:
  transforms: ['random_flip', 'pad', 'random_erase']
  sources: ['naic2019']
  targets: ['naic2019']

head:
  name: 'softmax'

loss:
  name: ['triplet', 'center', 'crossentropy']

train:
  batch_size: 64

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 64
  normalize_feature: True
  rerank: True
  eval_freq: 40