
model:
  backbone:
    name: 'resnet101_ibn_a'
  midneck:
    name: 'single_bnneck'

data:
  transforms: ['random_flip', 'random_crop', 'random_erase']
  sources: ['naic2019']
  targets: ['naic2019']

naic2019:
  phase: 'train'
  total: False

head:
  name: 'softmax'

loss:
  name: ['crossentropy', 'triplet', 'center']

train:
  batch_size: 64

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 64
  normalize_feature: True
  rerank: True
  eval_freq: 40