
model:
  backbone:
    pretrained: '/search/odin/tk/.torch/models/resnet50-19c8e357.pth'
  midneck:
    name: 'single_bnneck'

data:
  transforms: ['random_flip', 'random_crop', 'random_erase']
  sources: ['naic2019']
  targets: ['naic2019']

head:
  name: 'softmax'

loss:
  name: ['focal', 'ranked', 'center']

train:
  batch_size: 64

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 64
  normalize_feature: True
  rerank: True
  eval_freq: 40