
model:
  backbone:
    pretrained: '/search/odin/tk/.torch/models/resnet50-19c8e357.pth'
  midneck:
    name: 'single_bnneck'

data:
  transforms: ['random_flip', 'random_crop', 'random_erase']
  sources: ['naic2019']
  targets: ['naic2019']

head:
  name: 'arc'

loss:
  name: ['crossentropy', 'triplet', 'center']

solver:
  step_sizes: [[40, 70, 100, 130], None]
  gammas: [0.32, None]

train:
  batch_size: 64
  max_epoch: 150

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 64
  normalize_feature: True
  rerank: True
  eval_freq: 40