
model:
  backbone:
    pretrained: '/search/odin/tk/.torch/models/resnet50-19c8e357.pth'
  midneck:
    name: 'bnneck'

data:
  transforms: ['random_flip', 'random_crop', 'random_erase']
  sources: ['naic2019']
  targets: ['naic2019']

head:
  name: 'softmax'

loss:
  name: ['crossentropy', 'ranked', 'center']

naic2019:
  phase: 'train'
  total: False

train:
  batch_size: 128

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 128
  normalize_feature: True
  rerank: True
  eval_freq: 40